#!/usr/bin/env python3
#
# CSC469 - Performance Evaluation
#
# Daniel Bloemendal <d.bloemendal@gmail.com>
#

# Python imports
import os
import json

# Sample settings
MIN_ACTIVE   = 0.25
MAX_INACTIVE = 0.01

def format(data):
    # Scaling factor
    factor = (1/data['frequency'])*1e+3

    # Get start
    start = data['start']*factor

    # Scale the samples
    samples = [{'start': sample['start']*factor,
                'end'  : sample['end'  ]*factor} for sample in data['samples']]

    # Averages
    average = {'active': 0, 'inactive': 0, 'samples': 0}

    # Print the samples
    active = {'start': start, 'end': start}
    for i, inactive in enumerate(samples):
        # Set end of active period
        active['end'] = inactive['start']
        # Compute durations
        duration = {'active': active['end'] - active['start'],
                    'inactive': inactive['end'] - inactive['start']}
        # Add to averages if it is a valid period
        if(i > 0 and duration['active'] > MIN_ACTIVE
                 and duration['inactive'] < MAX_INACTIVE):
            average['active'] += duration['active']
            average['inactive'] += duration['inactive']
            average['samples'] += 1
        # Display the sample
        print('Active: {:5f}ms Inactive: {:5f}ms'.format(
            duration['active'], duration['inactive']))
        # Begin the next active period
        active['start'] = inactive['end']

    # Finish computing average
    for k in ['active', 'inactive']:
        average[k] /= average['samples']

    # Display averages
    print('Active Average: {active}\nInactive Average: {inactive}'.format(**average))

def main(arguments):
    ''' main program '''
    if len(arguments) > 1:
        try:
            datafile = open(arguments[1])
            data = json.load(datafile)
        except:
            print('Could not load data from "{}"'.format(arguments[1]))
        format(data)
    else:
        print('Usage: {} [<data file>]'.format(arguments[0]))

# Entry point
if __name__ == '__main__':
    from sys import argv
    main(argv)
